# Generated by Django 2.2.7 on 2019-11-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first', models.CharField(max_length=100)),
                ('last', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('stripe_number', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('approved_seller', models.BooleanField()),
                ('business_name', models.CharField(max_length=100)),
                ('business_address', models.CharField(max_length=100)),
                ('business_city', models.CharField(max_length=100)),
                ('business_state', models.CharField(max_length=100)),
                ('business_zip', models.CharField(max_length=50)),
                ('business_phone', models.CharField(max_length=30)),
                ('fein', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100, null=True)),
                ('balance', models.FloatField(default=0)),
                ('card_image', models.CharField(max_length=100, null=True)),
                ('website', models.CharField(max_length=150, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('address2', models.CharField(max_length=150, null=True)),
                ('city', models.CharField(max_length=150, null=True)),
                ('state', models.CharField(max_length=150, null=True)),
                ('zip', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardPurchased',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=10)),
                ('buyer', models.CharField(max_length=20)),
                ('seller', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('time_purchased', models.IntegerField(default=1574393897.019734)),
                ('redeemed', models.BooleanField(default=False)),
                ('redeemed_date', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=20)),
                ('seller', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('time_purchased', models.IntegerField(default=1574393897.020305)),
                ('associated_transaction', models.IntegerField()),
                ('card_purchased', models.CharField(max_length=10)),
            ],
        ),
    ]
