# Generated by Django 2.2.7 on 2019-11-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='cardpurchased',
            name='time_purchased',
            field=models.IntegerField(default=1574394802.177758),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time_purchased',
            field=models.IntegerField(default=1574394802.178216),
        ),
    ]
