# Generated by Django 2.2.7 on 2019-11-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191122_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpurchased',
            name='time_purchased',
            field=models.IntegerField(default=1574396092),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time_purchased',
            field=models.IntegerField(default=1574396092),
        ),
    ]
